import { copyFile, mkdir, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import { watch } from "node:fs";
import { dirname, extname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const contentRoot = join(projectRoot, "content");
const bookRoot = join(contentRoot, "zh", "books", "deconstructing_LLM");
const generatedRoot = join(projectRoot, ".generated");
const generatedModule = join(generatedRoot, "content.ts");
const generatedAssets = join(projectRoot, "public", "generated", "book-images");
const imageExtensions = new Set([".png", ".jpg", ".jpeg", ".webp", ".gif", ".avif", ".svg"]);

function posixPath(path) {
  return path.split(sep).join("/");
}

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries.sort((left, right) =>
    left.name.localeCompare(right.name, "zh-CN", { numeric: true })
  )) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await walk(path));
    if (entry.isFile()) files.push(path);
  }

  return files;
}

async function chapterIds() {
  const entries = await readdir(bookRoot, { withFileTypes: true });
  const candidates = entries
    .filter((entry) => entry.isDirectory() && /^chapter_\d+$/.test(entry.name))
    .map((entry) => entry.name)
    .sort((left, right) => left.localeCompare(right, "zh-CN", { numeric: true }));

  const published = await Promise.all(candidates.map(async (chapterId) => {
    const chapterEntries = await readdir(join(bookRoot, chapterId), { withFileTypes: true });
    return chapterEntries.some((entry) => entry.isFile() && extname(entry.name).toLowerCase() === ".md")
      ? chapterId
      : undefined;
  }));

  return published.filter(Boolean);
}

async function collectMarkdown() {
  const files = (await walk(contentRoot)).filter((path) => extname(path).toLowerCase() === ".md");
  const entries = await Promise.all(files.map(async (path) => {
    const key = `/content/${posixPath(relative(contentRoot, path))}`;
    return [key, await readFile(path, "utf8")];
  }));

  return Object.fromEntries(entries);
}

async function collectBookImages(ids) {
  await rm(generatedAssets, { recursive: true, force: true });
  const images = {};

  for (const chapterId of ids) {
    const sourceDirectory = join(bookRoot, chapterId, "images");
    const destinationDirectory = join(generatedAssets, chapterId);
    let entries = [];

    try {
      entries = await readdir(sourceDirectory, { withFileTypes: true });
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
    }

    images[chapterId] = {};
    for (const entry of entries
      .filter((candidate) => candidate.isFile() && imageExtensions.has(extname(candidate.name).toLowerCase()))
      .sort((left, right) => left.name.localeCompare(right.name, "zh-CN", { numeric: true }))) {
      await mkdir(destinationDirectory, { recursive: true });
      await copyFile(join(sourceDirectory, entry.name), join(destinationDirectory, entry.name));
      images[chapterId][`./images/${entry.name}`] = `/generated/book-images/${chapterId}/${entry.name}`;
    }
  }

  return images;
}

export async function generateContent() {
  const ids = await chapterIds();
  const [markdown, images] = await Promise.all([
    collectMarkdown(),
    collectBookImages(ids),
  ]);
  const source = [
    "// Generated by scripts/generate-content.mjs. Do not edit by hand.",
    `export const markdownContent: Record<string, string> = ${JSON.stringify(markdown, null, 2)};`,
    `export const bookChapterIds: string[] = ${JSON.stringify(ids, null, 2)};`,
    `export const bookImages: Record<string, Record<string, string>> = ${JSON.stringify(images, null, 2)};`,
    "",
  ].join("\n\n");

  await mkdir(generatedRoot, { recursive: true });
  const temporaryModule = `${generatedModule}.tmp`;
  await writeFile(temporaryModule, source, "utf8");
  await rename(temporaryModule, generatedModule);
  console.log(`内容索引已更新：${Object.keys(markdown).length} 篇 Markdown，${ids.length} 个章节目录。`);
}

export async function watchContent() {
  await generateContent();
  let timer;
  const watcher = watch(contentRoot, { recursive: true }, () => {
    clearTimeout(timer);
    timer = setTimeout(() => {
      generateContent().catch((error) => console.error("内容索引更新失败：", error));
    }, 120);
  });

  return () => {
    clearTimeout(timer);
    watcher.close();
  };
}

const invokedDirectly = process.argv[1]
  ? import.meta.url === pathToFileURL(resolve(process.argv[1])).href
  : false;

if (invokedDirectly) {
  if (process.argv.includes("--watch")) {
    await watchContent();
    console.log("正在监视 content/ 中的 Markdown 和图片……");
  } else {
    await generateContent();
  }
}
